
SCRIPT_COMMANDS = {
    'noop':             ('OP_NOOP',             []),
    'exit':             ('OP_EXIT',             []),
    'return':           ('OP_RET',              []),
    'jump':             ('OP_JUMP',             ['script']),
    'call':             ('OP_CALL',             ['script']),
    'start':            ('OP_START_SCRIPT',     ['script']),
    'wait':             ('OP_WAIT_SCRIPT',      ['activescript']),
    'stop_one':         ('OP_STOP_ONE_SCRIPT',  ['activescript']),
    'stop':             ('OP_STOP_SCRIPTS',     ['activescript']),
    'stop_all':         ('OP_STOP_ALL_SCRIPTS', []),
    'delay':            ('OP_DELAY',            ['uint']),
    'wait_state':       ('OP_WAIT_STATE',       ['uint']),
    'acquire_state':    ('OP_ACQUIRE_STATE',    ['uint']),
    'release_state':    ('OP_RELEASE_STATE',    ['uint']),
    'force_state':      ('OP_FORCE_STATE',      ['uint']),
    'dialog':           ('OP_SHOW_DIALOG',      ['string', '?actor']),
    'wait_dialog':      ('OP_WAIT_DIALOG',      []),
    'move_camera':      ('OP_MOVE_CAMERA',      ['target', 'float']),
    'move_water':       ('OP_MOVE_WATER',       ['float', 'float', '?color']),
    'set_gravity':      ('OP_SET_GRAVITY',      ['float', 'float']),
    'load_map':         ('OP_LOAD_MAP',         ['map', 'uint', '?color']),
    'change_music':     ('OP_CHANGE_MUSIC',     ['music', 'float', '?uint']),
    'play_sound':       ('OP_PLAY_SOUND',       ['actor', 'sfx', '?int']),
    'spawn_actor':      ('OP_SPAWN_ACTOR',      ['actortype', 'int', 'int',
                                                 '?uint', '?newtarget', '?angle']),
    'spawn_particles':  ('OP_SPAWN_PARTICLES',  ['target', 'fx',
                                                 ('flags', '?ushort'),
                                                 ('initframe', '?ushort'),
                                                 ('x', '?int'), ('y', '?int'),
                                                 ('w', '?ushort'), ('h', '?ushort'),
                                                 ('count', '?ushort'),
                                                 ('count_var', '?ushort'),
                                                 ('speed', '?ushort'),
                                                 ('speed_var', '?ushort'),
                                                 ('animspeed', '?ushort'),
                                                 ('animspeed_var', '?ushort'),
                                                 ('angle', '?angle'),
                                                 ('angle_var', '?angle')]),
    'set_actor_state':  ('OP_SET_ACTOR_STATE',  ['actor', 'uint', 'uint']),
    'set_actor_target': ('OP_SET_ACTOR_TARGET', ['actor', 'target']),
    'damage_actor':     ('OP_DAMAGE_ACTOR',     ['actor', 'uint', 'uint']),
    'destroy_actor':    ('OP_DESTROY_ACTOR',    ['actor']),
    'earthquake':       ('OP_EARTHQUAKE',       ['uint', 'uint']),
    'wait_earthquake':  ('OP_WAIT_EARTHQUAKE',  []),
}

