#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  AT_TRIGGER,
  AT_YELLOW,
  AT_PINK,
  AT_BLUE,
  AT_CRATE,
  AT_CRATE_BIG,
  AT_MUSH_SPRING_SM,
  AT_MUSH_SPRING_BIG,
  AT_WALKER,
  AT_CRAB,
  AT_PIRANHA,
  AT_PIRANHA_BIG,
  AT_DART_FISH,
  AT_OCTOPUS,
  AT_FLY_DEMON,
  AT_MEERMAN,
  AT_MINE_SM,
  AT_MINE_MED,
  AT_MINE_BIG,
  AT_CRYSTAL_BIG,
  AT_CRYSTAL_SM,
  AT_POWERUP,
  AT_CLIFF_PLATFORM_BIG,
  AT_CLIFF_PLATFORM_SM_1,
  AT_CLIFF_PLATFORM_SM_2,
  AT_CLIFF_PLATFORM_SM_3,
  AT_UNDERWATER_PLATFORM,
  AT_SPACESHIP,
  AT_SUBMARINE,
  NUM_ACTORS,
} actor_type_t;

#ifdef __cplusplus
}
#endif

