#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  OP_NOOP,
  OP_EXIT,
  OP_RET,
  OP_JUMP,
  OP_CALL,
  OP_EXEC,
  OP_SINGLETON,
  OP_START_SCRIPT,
  OP_WAIT_SCRIPT,
  OP_STOP_ONE_SCRIPT,
  OP_STOP_SCRIPTS,
  OP_STOP_ALL_SCRIPTS,
  OP_DELAY,
  OP_WAIT_STATE,
  OP_ACQUIRE_STATE,
  OP_RELEASE_STATE,
  OP_FORCE_STATE,
  OP_SHOW_DIALOG,
  OP_WAIT_DIALOG,
  OP_MOVE_CAMERA,
  OP_MOVE_WATER,
  OP_SET_GRAVITY,
  OP_LOAD_MAP,
  OP_CHANGE_MUSIC,
  OP_PLAY_SOUND,
  OP_SPAWN_ACTOR,
  OP_SPAWN_PARTICLES,
  OP_SET_ACTOR_STATE,
  OP_SET_ACTOR_TARGET,
  OP_DAMAGE_ACTOR,
  OP_DESTROY_ACTOR,
  OP_EARTHQUAKE,
  OP_WAIT_EARTHQUAKE,
} script_op_t;

#ifdef __cplusplus
}
#endif
